### ISSUE TITLE
\begin and \end do not work

### ISSUE THREAD

**Issue by rennmaus-coder** [ForNeVeR/wpf-math#324] opened 2022-12-29 09:17 UTC
When I try to use \begin and \end, it gives me this error:

```Ausnahme ausgelöst: "WpfMath.Exceptions.TexParseException" in WpfMath.dll
Unknown symbol or command or predefined TeXFormula: 'begin'

Ausnahme ausgelöst: "WpfMath.Exceptions.TexParseException" in WpfMath.dll
Unknown character : '&'

Ausnahme ausgelöst: "WpfMath.Exceptions.TexParseException" in WpfMath.dll
Unknown character : '&'

Ausnahme ausgelöst: "WpfMath.Exceptions.TexParseException" in WpfMath.dll
Unknown symbol or command or predefined TeXFormula: 'end'
```

I am trying to use a matrix here, the LaTeX code is: 
```
\begin{pmatrix}
                           a & b\\ c & d
                           \end{pmatrix}
                           \begin{pmatrix}
                           \alpha & \beta \\ \gamma & \delta
                           \end{pmatrix} = 
                           \begin{pmatrix}
                           a\alpha + b\gamma & a\beta + b \delta \\
                           c\alpha + d\gamma & c\beta + d \delta 
                           \end{pmatrix}
```
I hope this can be fixed. I can't use \matrix, because that is incompatible with https://github.com/verybadcat/CSharpMath which I use for an app

**Comment by ForNeVeR** [comment] 2022-12-29 19:30
Duplicate of #191. Should be technically possible to implement; please send a contribution!

**Closed by ForNeVeR** 2022-12-29 19:30 UTC
