### ISSUE TITLE
Exception "The type initializer for 'WpfMath.TexFormulaParser' threw an exception."

### ISSUE THREAD

**Issue by Angourisoft** [ForNeVeR/wpf-math#224] opened 2019-11-07 18:33 UTC
When trying to create an instance of TexFormulaParser:
`
var parser = new TexFormulaParser();
`
getting an error with text "The type initializer for 'WpfMath.TexFormulaParser' threw an exception."

VS 2019, last version. Tried wmf 0.7.0, 0.5.0, 0.6.0. Tried to create an empty project, the error remains.

**Comment by ForNeVeR** [comment] 2019-11-09 11:22
Well, which exception did it threw?

**Comment by Angourisoft** [comment] 2019-11-09 11:27
The one mentioned in the title. There was also an "inner exception" (that I found out later) about something connected with "core assembly". Sorry that I don't have the exact text of the error. Some extra info: win10, the c# program is dot net web core site.

**Comment by ForNeVeR** [comment] 2019-11-09 12:22
So, are you trying to use WPF-Math with .NET Core already? Could you please upload the sample project somewhere?

If it's true, then my answer would be: we don't support WPF on .NET Core (yet), and this is planned for the nearest future.

Also, we haven't tried to run WPF-Math on .NET Core as-is, and I don't know if it's supposed to run or not. Probably you better wait for official support of WPF on .NET Core before trying that.

**Comment by Angourisoft** [comment] 2019-11-09 16:16
Thank you for the reply, that seems to be the cause. Yes, Im running it on .NET Core. I can't upload a sample project, but it is easy to make this error occur (create .Net project > type "new TexFormulaParser();" )

**Comment by ForNeVeR** [comment] 2019-11-10 07:54
Okay, then I'm closing this as a duplicate of #209.

**Closed by ForNeVeR** 2019-11-10 07:54 UTC
Labels: kind:bug
