### ISSUE TITLE
Superscript at the end of the string results in error

### ISSUE THREAD

**Issue by illiteratePhD** [ForNeVeR/wpf-math#73] opened 2017-03-14 22:40 UTC
Trying the following string will yield an error:

```tex
d_{f,t}(u,v) = \sum_{x, y}\left(f(x, y) - t(x - u, y - v)\right)^2
```

**Comment by gsomix** [comment] 2017-03-15 10:26
Duplicate of #62

**Comment by ForNeVeR** [comment] 2017-03-15 11:11
Merged into #62.

**Closed by ForNeVeR** 2017-03-15 11:11 UTC
Labels: kind:bug, resolution:duplicate

**Comment by ForNeVeR** [comment] 2017-03-18 05:26
@illiteratePhD please note that we have fixed the issue with #74.

**Comment by illiteratePhD** [comment] 2017-03-18 20:05
@ForNeVeR Fantastic! Going to check it out as soon as I am able. Great work guys!
